### ISSUE TITLE
RSS feed issues after update

### ISSUE THREAD

**Issue by ErikJson** [laravelnews/site-bugs#1]
Hi Eric,

I noticed my Feedly had a small explosion of unread articles, and it turned out it was due to all the articles in the Laravel news feed being marked as updated the hour before. Not a huge issue as I will simply tick off the ones I already read, but I thought I would let you know.

Keep up the good work :)

**Comment by ericlbarnes** [comment]
👍 I was actually concerned about that and remembered from years ago if you kept the RSS XML exactly the same it wouldn't do that, but then I forgot to double check before hitting the deploy button. 

I'll double check it, but I think it should be corrected going forward.
