### ISSUE TITLE
[Feature] Add "color hints" & "filter" for different topics of post.

### ISSUE THREAD

**Issue by cirdog** [laravelnews/site-bugs#11]
I like the clean UI very much.

But I got dazzled while looking at/for the **Topics** (top bold text of each box). I could not **easily identify** the topics that interest me at a glance, and I could not **filter the topic** I want to browse.

Here I attached a screen with my rough ideas on it _(fat & slim box overlay, or colored text),_ hopefully your web designer can come up with a proper & elegant style for these features, if you also feel that they are useful.

Thanks.

![laravel-links](https://cloud.githubusercontent.com/assets/172924/19184657/c5fe2d5c-8cb0-11e6-95f7-5c4460628f10.png)

**Comment by ericlbarnes** [comment]
Thanks and sorry for the delay. I didn't get notified for some reason. 

I like this idea!
