### ISSUE TITLE
Broken article image

### ISSUE THREAD

**Issue by mattsbanner** [laravelnews/site-bugs#15]
I'm seeing an issue with the loading of an image on the article "Building maintainable PHP apps using Composer". Looks like it could be broken markdown.

![Screenshot 2021-04-11 at 20 07 45](https://user-images.githubusercontent.com/49304331/114317777-9e6abd00-9b01-11eb-88c5-6a14f7455b24.png)

https://laravel-news.com/building-apps-composer

**Comment by ericlbarnes** [comment]
Thanks! Fixed now.
