### ISSUE TITLE
Incorrect composer command

### ISSUE THREAD

**Issue by GromNaN** [laravelnews/site-bugs#18]
Hello,

I tried your article on ["Laravel Tutorial: Step by Step Guide to Building Your First Laravel Application"](https://laravel-news.com/your-first-laravel-application). This is the best get started article I found, thank you.
In "Authentication Scaffolding" chapter, I think the command to install `laravel/ui` with composer is incorrect. It should be fixed like this:

```diff
- composer install laravel/ui
+ composer require laravel/ui
```

**Comment by ericlbarnes** [comment]
Thanks! Fixing now.
