### ISSUE TITLE
SSL Certificate issue: The connection to email.mg.laravel-news.com is not secure

### ISSUE THREAD

**Issue by tisuchi** [laravelnews/site-bugs#19]
Hi,

I attempted to submit a community link and was prompted to log in. During the login process, I was asked to verify my account.

<img width="456" alt="image" src="https://github.com/laravelnews/site-bugs/assets/2137978/0fff7fec-afc7-47d7-b77d-af25b4801806">

However, upon requesting and then clicking the verification link, I encountered a Not Secure warning.

<img width="1017" alt="image" src="https://github.com/laravelnews/site-bugs/assets/2137978/111be6d2-19a1-498f-b933-1a3aadbf934d">

**Comment by ericlbarnes** [comment]
Thanks! I believe I have this fixed now. Accidentally had Mailgun set up to track links, and it was rewriting them. Can you try again?
