### ISSUE TITLE
Not loading "trending community links"

### ISSUE THREAD

**Issue by robindirksen1** [laravelnews/site-bugs#20]
When you are on the page https://laravel-news.com/links?sort=new, and click on the "trending"-filter, you are redirected to https://laravel-news.com/links, but the content isn't showing trending items.

Screenshots:
- [With new-filter](https://github.com/laravelnews/site-bugs/assets/22446895/7ed86ed6-8500-40a6-9cdc-8aeba3034dd0) 
- [With trending-filter, coming from new-filter - incorrect content](https://github.com/laravelnews/site-bugs/assets/22446895/f8e66a63-b2ef-4927-8168-4685d4f3a9bf)

**Comment by ericlbarnes** [comment]
I separated this into two sep pages, and it should be fixed now.
