### ISSUE TITLE
Remove redundant line from RSS items

### ISSUE THREAD

**Issue by pindab0ter** [laravelnews/site-bugs#23]
Every RSS item ends with “The post [post name] appeared first on Laravel News.”

I’ve always thought this is a very odd line, as most—if not all—posts _only_ appear there. We also already know where the post is from, as that’s the feed I’m subscribed to.

Finally, the link it provides to the post is redundant, as that is also provided by the meta data, which is read by most—if not all—RSS readers.

Instead, I would much rather see the entire content of the post.

P.s.: Thanks for all the work on this site! It’s very valuable to me!

**Comment by ericlbarnes** [comment]
Just made it a full feed: https://feed.laravel-news.com/ 

I did keep the lines at the bottom because I know many sites used to scrap RSS feeds and basically steal the content. This at least gives me a link back, in those situations.

**Comment by pindab0ter** [comment]
Thank you for making it a full feed! It is much appreciated!

I understand the requirement for a link back in case of scraping. In that context the sentence actually makes sense.

Again, thank you for doing this, and so quickly, too!
