### ISSUE TITLE
RSS feed missing title

### ISSUE THREAD

**Issue by simon-tma** [laravelnews/site-bugs#24]
The JSON RSS feed (https://laravel-news.com/feed/json) is missing a title, so is now showing as `[Untitled]` rather than as `Laravel News`

<img width="107" alt="Screenshot 2023-10-03 at 09 59 19" src="https://github.com/laravelnews/site-bugs/assets/37322653/fcc15369-0350-4ebb-a033-89fadf079c2c">

**Comment by ericlbarnes** [comment]
Thanks! Pushing fix now. 🫡
