### ISSUE TITLE
Search functionality is not working

### ISSUE THREAD

**Issue by eura-app** [laravelnews/site-bugs#25]
Search functionality is not working.

In the network tab i can see failed requests to:

https://undefined-2.algolianet.com/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(4.20.0)%3B%20Browser%20(lite)%3B%20instantsearch.js%20(4.56.11)%3B%20JS%20Helper%20(3.14.1)&x-algolia-api-key=undefined&x-algolia-application-id=undefined

**Comment by ericlbarnes** [comment]
Thanks! Fixed now.
