### ISSUE TITLE
Search text box javascript error.

### ISSUE THREAD

**Issue by vaweto** [laravelnews/site-bugs#26]
While writing on search box i'am getting an Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length').

This is from search widget on that code ${t.excerpt.length > 150 ? t.excerpt.substring(0, 150) + "..." : t.excerpt}

**Comment by ericlbarnes** [comment]
That's odd, and I'm not duplicating with safari or brave. What browser are you using?

**Comment by vaweto** [comment]
From M1 macbook with Version 116.0.5845.179 of chrome and from a mobile version of chrome

![Untitled 3](https://github.com/laravelnews/site-bugs/assets/14108100/647b2374-1744-430a-84d5-429d0dfbf2e4)

**Comment by ericlbarnes** [comment]
That was weird. I did duplicate it in chrome. I just did a rebuild of the assets and I think it's fixed now. Might need to do a hard refresh "just incase".

**Comment by vaweto** [comment]
I think I found the problem. The error happened when you search for something that does not exist. So the excerpt is empty because it returns nothing.

**Comment by ericlbarnes** [comment]
Thanks! Updated now. Can you try again?

**Comment by vaweto** [comment]
It's all good now!!

**Comment by ericlbarnes** [comment]
🎉
