### ISSUE TITLE
Profiles of authors some get 404 message

### ISSUE THREAD

**Issue by eura-app** [laravelnews/site-bugs#27]
When clicking on the author below a blog post to see his profile and their past blogs i get at sometimes a 404 error.

Works:
https://laravel-news.com/php-desktop-and-mobile-user-agent-parser
When clicking below the post on the author profile Paul Redmond
You go to https://laravel-news.com/@paulredmond

Does not work:
https://laravel-news.com/sharp-for-laravel
When clicking below the post on the author profile Philippe Lonchampt
You go to https://laravel-news.com/@dvlpp
And get a 404

https://laravel-news.com/laravel-lift
When clicking below the post on the author profile Wendell Adriel
You go to https://laravel-news.com/@wendell_adriel
And get a 404

**Comment by ericlbarnes** [comment]
Thanks! Fixed now.
