### ISSUE TITLE
Links no more published on social networks

### ISSUE THREAD

**Issue by mho22** [laravelnews/site-bugs#31]
Hi Laravel News Team,

First of all, thank you for your amazing work!

Over the past three months, I’ve noticed a few issues:

- Approved articles are no longer being published on social media.
- I no longer receive email notifications when my articles are approved.
- I’ve stopped receiving the newsletter, which appears to have been stuck at #536 (likely from the third week of October).

I’m unsure if these changes are due to a new publication policy, but they seem like potential bugs.

<img width="1178" alt="Capture d’écran 2024-12-04 à 10 49 30" src="https://github.com/user-attachments/assets/5165efb0-20b0-4b6f-9f8c-b417c5a660e4">

On this screenshot, the last one has been published on socials. The three others have not.

**Comment by ericlbarnes** [comment]
Thanks for the report. I'll look into this and see if I can spot what it is going on.

**Comment by ericlbarnes** [comment]
You should have just gotten two emails with approvals. Looks like we had a queue issue. 😬

Checking the auto share stuff now.

**Comment by mho22** [comment]
I was just in the process of writing to let you know that I did indeed receive two emails with approvals. Thank you! Let's see if social networks and newsletter will share them too.

**Comment by ericlbarnes** [comment]
I think it's all back to working now: 
https://x.com/LaravelLinks/status/1864387361569706352

**Comment by mho22** [comment]
Thank you for your time
