### ISSUE TITLE
page with all tags

### ISSUE THREAD

**Issue by hifron** [laravelnews/site-bugs#32]
There is missing page with all tags, maybe at footer or as https://laravel-news.com/sitemap_tags.xml but that seems weird...

or

There could be categorization of tags and make count of articles of that, but all tags on same page... Maybe something like https://discussions.unity.com/tags

currently there are tags filled only in article and also in https://laravel-news.com/feed/json,
butt: How to know there is some vscode tag if there is no Larry Page?

**Comment by ericlbarnes** [comment]
Thanks! 
Working on adding an "all tags" page now and you can see it here: 
https://laravel-news.com/tags

**Comment by hifron** [comment]
Maybe https://laravel-news.com/sitemap_articles.xml could have tags in it... _if desired_, but feeds also if desired have various formats like rss or atom but not sure if they have capability for tags feature, today's readers are not so advanced(maybe liferea or liferay :) so it is grey economy mostly pruned for advanced things with sugar UI wanted and advanced readers are not so common...

ALL wordpress sites have capability for /feed so it is also somehow hidden :)

**Comment by ericlbarnes** [comment]
Not sure if I understand, but if you are looking for an RSS feed, we have that here: 
https://feed.laravel-news.com 

It should be compatible with any feed reader.
