### ISSUE TITLE
Site looks broken

### ISSUE THREAD

**Issue by tomicakorac** [laravelnews/site-bugs#4]
Hi, the new site is broken in Opera 39 on Linux 16.04. I'm attaching a few screenshots:

![screenshot from 2016-08-07 09-35-30](https://cloud.githubusercontent.com/assets/2043263/17461165/b5caeae6-5c82-11e6-8d67-bf7c05656b41.png)
![screenshot from 2016-08-07 09-35-41](https://cloud.githubusercontent.com/assets/2043263/17461164/b5c33bd4-5c82-11e6-85c6-a06a38113e4a.png)
![screenshot from 2016-08-07 09-35-46](https://cloud.githubusercontent.com/assets/2043263/17461167/bb9bd782-5c82-11e6-8306-ab1ec27168fe.png)
![screenshot from 2016-08-07 09-35-51](https://cloud.githubusercontent.com/assets/2043263/17461168/c3678a38-5c82-11e6-975a-de15f8d67485.png)

**Comment by ericlbarnes** [comment]
It looks like the css isn't loading. Are you noticing anything in the network pane?

**Comment by tomicakorac** [comment]
Nothing unexpected in the Network pane, but this is shown in the Error Console:

```
(index):19 GET https://laravel-news.com/build/assets/css/all-a9e288ce09.css 
(index):56 GET https://laravel-news.com/assets/images/min/ln-logo.png 403 ()
(index):97 GET https://laravel-news.com/assets/images/min/dark-ln-elephant.png 403 ()
(index):120 GET https://laravel-news.com/assets/images/min/icon-newsletter.png 403 ()
(index):164 GET https://laravel-news.com/assets/images/min/icon-chair.png 403 ()
(index):380 GET https://laravel-news.com/assets/images/min/zaengle-logo.png 403 ()
(index):408 GET https://laravel-news.com/build/assets/js/app-53f82857cb.js 
pro.js:1 GET https://srv.buysellads.com/ads/get/ids/CVSIL53Y/?r=1470643200000 _bsaPRO @ pro.js:1pc.onload @ bsa.js:1
favicon-16x16.png:1 GET https://laravel-news.com/favicon-16x16.png 403 ()
favicon-32x32.png:1 GET https://laravel-news.com/favicon-32x32.png 403 ()
```

CSS itself and the JS files don't have any error code associated to them, but still aren't loading. The PNGs return 403 Forbidden. However both the CSS and the other resources are fully accessible if I open them directly.

Could this be a permissions issue?

**Comment by ericlbarnes** [comment]
I haven't had any other reports on this and asked on twitter. One of the replies said: 

> @ericlbarnes I wonder if he has that opera VPN / proxy feature turned on and that’s somehow confusing things. Shot in the dark.

I don't really have any ideas I'm afraid. I think it would have to be either cloudflare or maybe http/2 stuff but I believe it should work with most current browsers.

**Comment by mstaack** [comment]
its working fine for me with:  

```
Version:    39.0.2256.48 - Opera ist auf dem neuesten Stand
Update-Stream:  Stable
Betriebssystem: Ubuntu 16.04.1 LTS (x86_64; Unity)

```

**Comment by tomicakorac** [comment]
@ericbarnes I do usually keep Opera's ad blocker on  and that was my first thought too. But turning it off didn't help unfortunately. These screenshots were made with Ad Blocker off.

Also, I use Tor proxy service globally on my system. I'm not sure how that could cause any problems of this kind though, especially since I am only experiencing this issue on your site, out of thousands I've visited through Tor in the past couple of months.

@mstaack thanks for your input. That's pretty strange, since my configuration's the same. Do you have Ad Blocker or Opera Turbo or Opera Battery Saver enabled or not?

**Comment by tomicakorac** [comment]
This issue seems to be gone now. Thanks all.
